accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from accounts import views

# Set the application namespace
app_name = 'accounts'

# URL patterns for the accounts app
urlpatterns = [
    # URL pattern for user registration
    path('register/', views.user_register, name='user_register'),
    # URL pattern for user login
    path('login/', views.user_login, name='user_login'),
    # URL pattern for manager login
    path('login/manager/', views.manager_login, name='manager_login'),
    # URL pattern for user logout
    path('logout/', views.user_logout, name='user_logout'),
    # URL pattern for editing user profile
    path('profile/edit', views.edit_profile, name='edit_profile'),
    # URL pattern for password reset
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',  # Template for password reset
            success_url=reverse_lazy('accounts:password_reset_done'),  # Redirect URL on success
            email_template_name='email_template.html'  # Email template for password reset
        ),
        name='password_reset'
    ),
    # URL pattern for password reset done
    path(
        'password-reset/done',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password_reset_done.html',  # Template for password reset done
        ),
        name='password_reset_done'
    ),
    # URL pattern for password reset confirm
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html',  # Template for password reset confirm
            success_url=reverse_lazy('accounts:password_reset_complete'),  # Redirect URL on success
        ),
        name='password_reset_confirm'
    ),
    # URL pattern for password reset complete
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html',  # Template for password reset complete
        ),
        name='password_reset_complete'
    ),
]

accounts/templates/accounts/edit_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <!-- Container for the form with Bootstrap class to control width and alignment -->
    <div class="col-md-6">
        <!-- Form element with POST method for secure data submission -->
        <form method="POST">
            <!-- CSRF token for security to prevent Cross-Site Request Forgery attacks -->
            {% csrf_token %}
            <!-- Heading for the form -->
            <h3>Edit Profile</h3>
            <!-- Horizontal line for visual separation -->
            <hr>
            <!-- Render the form fields using crispy forms for Bootstrap styling -->
            {{ form|crispy  }}
            <!-- Container for the submit button with Bootstrap class for styling -->
            <div class="form-group">
                <!-- Submit button with Bootstrap classes for styling -->
                <button class="btn btn-primary mt-3 w-100" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/email_template.html
{% load i18n %}{% autoescape off %}

<!-- Block for translation of a message informing the user about the password reset request -->
{% blocktranslate %}
You're receiving this email because you requested a password reset for your user account at {{ site_name }}.
{% endblocktranslate %}

<!-- Translation of the instruction to go to the provided page to set a new password -->
{% translate "Please go to the following page and choose a new password:" %}

<!-- Block for the password reset link. This uses the protocol, domain, and URL token to generate the full reset link -->
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

<!-- Translation of the message providing the username in case the user has forgotten it -->
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

<!-- Translation of a thank you message to the user for using the site -->
{% translate "Thanks for using our site!" %}

<!-- Block for translation of the closing message from the site team -->
{% blocktranslate %}
The {{ site_name }} team
{% endblocktranslate %}

{% endautoescape %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <!-- Container for the form with Bootstrap class to control width and alignment -->
    <div class="col-md-6">
        <!-- Form element with POST method for secure data submission -->
        <form method="POST">
            <!-- CSRF token for security to prevent Cross-Site Request Forgery attacks -->
            {% csrf_token %}
            <!-- Heading for the form -->
            <h3>Login</h3>
            <!-- Horizontal line for visual separation -->
            <hr>
            <!-- Render the form fields using crispy forms for Bootstrap styling -->
            {{ form|crispy }}
            <!-- Container for the submit button with Bootstrap class for styling -->
            <div class="form-group">
                <!-- Submit button with Bootstrap classes for styling -->
                <button class="btn btn-primary mt-3 w-100" type="submit">Submit</button>
            </div>
            <!-- Additional div for the forgot password link with margin-top and margin-bottom classes -->
            <div class="mt-2 mb-2">
                <small class="">
                    <!-- Forgot password link with Bootstrap classes for text styling -->
                    <a class="text-decoration-none text-danger" href="{% url 'accounts:password_reset' %}">Forgot Password?</a>
                </small>
            </div>
        </form>
        <!-- Div for the new account creation link with a top border and padding-top class -->
        <div class="border-top pt-3">
            <small class="text-muted">
                <!-- New account creation link with Bootstrap classes for text styling -->
                New Here? <a class="text-decoration-none" href="{% url 'accounts:user_register' %}">Create account</a>
            </small>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/manager_login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Character set declaration -->
    <meta charset="UTF-8" />
    <!-- Compatibility mode for IE -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Bootstrap CSS for styling -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/>
    <!-- Viewport settings for responsive design -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Title of the page -->
    <title>Dashboard</title>
  </head>
  <body>
    <!-- Main container for the content -->
    <main class="container">
      <!-- Row for organizing layout, with margin-top and text capitalization classes -->
      <div class="row mt-5 text-capitalize">
        <!-- Empty columns for centering the form -->
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <!-- Form element with POST method for secure data submission, and top margin and padding classes -->
          <form method="post" class="mt-5 pt-5">
            <!-- CSRF token for security to prevent Cross-Site Request Forgery attacks -->
            {% csrf_token %}
            <!-- Form heading -->
            <h2>Dashboard</h2>
            <!-- Django form rendering -->
            {{ form }}
            <!-- Submit button with full width, primary styling, and top margin classes -->
            <button class="w-100 btn btn-primary mt-3" type="submit">Sign In</button>
          </form>
          <!-- Paragraph with muted text color and top margin for the back to shop link -->
          <p class="text-muted mt-3">
            <!-- Link to the shop home page with URL tag -->
            <a href="{% url 'shop:home_page' %}">Back to shop</a>
          </p>
        </div>
        <!-- Empty columns for centering the form -->
        <div class="col-md-4"></div>
      </div>
    </main>
  </body>
</html>

accounts/templates/accounts/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <!-- Container for the form with Bootstrap class to control width and alignment -->
    <div class="col-md-6">
        <!-- Form element with POST method for secure data submission -->
        <form method="POST">
            <!-- CSRF token for security to prevent Cross-Site Request Forgery attacks -->
            {% csrf_token %}
            <!-- Heading for the form -->
            <h3>Reset Password</h3>
            <!-- Horizontal line for visual separation -->
            <hr>
            <!-- Instructional text for the user with a Bootstrap class for text styling -->
            <p class="text-danger">Please enter your email that you used in your account.</p>
            <!-- Render the form fields using crispy forms for Bootstrap styling -->
            {{ form|crispy }}
            <!-- Container for the submit button with Bootstrap class for styling -->
            <div class="form-group">
                <!-- Submit button with Bootstrap classes for styling -->
                <button class="btn btn-primary mt-3 w-100" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <!-- Container for the success message with Bootstrap class for width and alert styling -->
    <div class="col-md-6 alert alert-success">
        <!-- Success message indicating the password has been set -->
        Your Password Has Been Set.
    </div>
    <!-- Link to the login page with URL tag and optional class for styling -->
    <a href="{% url 'accounts:user_login' %}" class="">Login Here</a>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <!-- Container for the form with Bootstrap class to control width and alignment -->
    <div class="col-md-6">
        <!-- Form element with POST method for secure data submission -->
        <form method="POST">
            <!-- CSRF token for security to prevent Cross-Site Request Forgery attacks -->
            {% csrf_token %}
            <!-- Heading for the form -->
            <h3>Reset Password</h3>
            <!-- Horizontal line for visual separation -->
            <hr>
            <!-- Render the form fields using crispy forms for Bootstrap styling -->
            {{ form|crispy }}
            <!-- Container for the submit button with Bootstrap class for styling -->
            <div class="form-group">
                <!-- Submit button with Bootstrap classes for styling -->
                <button class="btn btn-primary mt-3 w-100" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <!-- Container for the information message with Bootstrap class for width and alert styling -->
    <div class="col-md-6 alert alert-info">
        <!-- Information message indicating that an email has been sent with instructions to reset the password -->
        An Email has been sent with instructions to reset your password!
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <!-- Container for the form with Bootstrap class to control width and alignment -->
    <div class="col-md-6">
        <!-- Check if there are any messages to display -->
        {% if messages %}
        <div>
            <!-- Loop through each message and display it -->
            {% for message in messages %}
                <!-- Alert box for each message with conditional classes based on message tags -->
                <div class="alert {% if message.tags %} alert-{{ message.tags }} {% else %} alert-info {% endif %} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <!-- Button to close the alert box -->
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        </div>
        {% endif %}
        <!-- Form element with POST method for secure data submission -->
        <form method="POST">
            <!-- CSRF token for security to prevent Cross-Site Request Forgery attacks -->
            {% csrf_token %}
            <!-- Heading for the form -->
            <h3>Create Account</h3>
            <!-- Horizontal line for visual separation -->
            <hr>
            <!-- Render the form fields using crispy forms for Bootstrap styling -->
            {{ form|crispy }}
            <!-- Container for the submit button with Bootstrap class for styling -->
            <div class="form-group">
                <!-- Submit button with Bootstrap classes for styling -->
                <button class="btn btn-primary w-100 mt-2" type="submit">Submit</button>
            </div>
        </form>
        <!-- Additional text and link for users who already have an account -->
        <div class="mt-3">
            <small class="text-muted">
                Already have an account? <a href="{% url 'accounts:user_login' %}">Login</a>
            </small>
        </div>
    </div>
{% endblock %}